SELECT *FROM hr.employees;

SELECT MAX(SALARY) FROM hr.employees;

SELECT MIN(SALARY) FROM hr.employees;

SELECT MAX(SALARY)-MIN(SALARY) FROM hr.employees;

SELECT JOB_ID, AVG(SALARY) FROM hr.employees GROUP BY JOB_ID ORDER BY AVG(SALARY) DESC;

SELECT SUM(SALARY) FROM hr.employees;

SELECT ROUND(MAX(SALARY), 2), ROUND(MIN(SALARY), 2), ROUND(SUM(SALARY), 2), ROUND(AVG(SALARY), 2) FROM hr.employees;

SELECT JOB_ID, COUNT(*) FROM hr.employees GROUP BY JOB_ID HAVING JOB_ID = 'IT_PROG';

SELECT JOB_ID, SUM(SALARY) FROM hr.employees GROUP BY JOB_ID;

SELECT JOB_ID, SUM(SALARY) FROM hr.employees GROUP BY JOB_ID HAVING JOB_ID = 'IT_PROG';

SELECT JOB_ID, AVG(SALARY) FROM hr.employees GROUP BY JOB_ID HAVING NOT JOB_ID = 'IT_PROG' ORDER BY AVG(SALARY) DESC;

SELECT AVG(SALARY), COUNT(*) FROM hr.employees GROUP BY DEPARTMENT_ID HAVING COUNT(*) > 10;

SELECT PHONE_NUMBER FROM hr.employees;

SET SQL_SAFE_UPDATES = 0;

UPDATE hr.employees SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515', '777') WHERE PHONE_NUMBER LIKE '515%';