version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: container_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker123
    ports:
      - 3306:3306
  api:
    container_name: api
    image: node:16
    restart: always
    ports:
      - 3001:3001
    environment:
      - DB_HOST=mysql
      - DB_NAME=orm_example
      - DB_USER=root
      - DB_PASSWORD=docker123
      - SERVER_PORT=3001
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    command: bash
    tty: true
    stdin_open: true
    depends_on:
      - mysql